# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml

- name: List all reservations
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  tasks:
    - name: List all reservations
      phoenixnap.bmc.reservation_info:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
        product_category: bandwidth
      register: output
    - name: Print the gathered infos
      ansible.builtin.debug:
        var: output.reservations
