# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml

- name: Delete public network
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  tasks:
    - name: Delete public network
      phoenixnap.bmc.public_network:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
        name: Initial public network
        state: absent
      register: output
    - name: Print the networks information
      ansible.builtin.debug:
        var: output.public_networks
