# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml

- name: Example
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  tasks:
    - name: Delete the SSH Key
      phoenixnap.bmc.ssh_key:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
        name: sshkey-name-01
        state: absent
      register: output
    - name: Print the gathered infos
      ansible.builtin.debug:
        var: output.ssh_keys
