# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml

- name: Example
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  tasks:
    - name: Show all ssh keys
      phoenixnap.bmc.ssh_key_info:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
        # filter by name
        # names: [my-ssh-key-1, my-ssh-key-2]
      register: output
    - name: Print the gathered infos
      ansible.builtin.debug:
        var: output.ssh_keys
