# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml

- name: Example
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  tasks:
    - name: Create new clusters | management and workload
      phoenixnap.bmc.cluster:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
        location: PHX
        name: Rancher cluster deployment
        description: mydescritpion
        node_server_type: s1.c1.small
        node_pool_count: 1
        node_install_default_keys: false
        node_key_ids: 6xex7xbx7xex1x4x3xfxex3x, 6yfy6y4yby6ydy2y4ycy2ybyXyX
        workload_configuration:
          name: Workload cluster
          location: PHX
          server_count: 1
          server_type: s2.c2.small
        state: present
      register: output
    - name: Print the cluster information
      ansible.builtin.debug:
        var: output.clusters
