# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml

- name: Example
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  tasks:
    - name: Create new tag for account
      phoenixnap.bmc.tag:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
        name: Environment
        description: This tag is used for all resources that need to be assigned to an environment.
        is_billing_tag: false
        state: present
      register: output
    - name: Print the tag information
      ansible.builtin.debug:
        var: output.tags
