# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml
# and generated SSH key pair in location: ~/.ssh/

- name: Example
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  tasks:
    - name: Create two ubuntu servers
      phoenixnap.bmc.server:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
        hostnames: [my-server-1, my-server-2]
        location: PHX
        os: ubuntu/bionic
        type: s1.c1.medium
        ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
      register: output
    - name: Print the servers information
      ansible.builtin.debug:
        var: output.servers
