# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml
# and generated SSH key pair in location: ~/.ssh/

- name: Example
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  tasks:
    - name: Create new server | network example
      phoenixnap.bmc.server:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
        hostnames: my-server-1
        description: My custom server 1
        location: PHX
        os: ubuntu/bionic
        type: s0.d1.medium
        gateway_address: 182.16.0.145
        private_network_configuration_type: USER_DEFINED
        private_networks:
          - id: 60f81608e2f4665962b214db
            ips: [10.0.0.13 - 10.0.0.17]
            dhcp: false
          - id: 60f93142c5c1d6082d31382a
            ips: [10.0.0.11, 10.0.0.12]
            dhcp: false
        public_networks:
          - id: 60473c2509268bc77fd06d29
            ips: [182.16.0.146, 182.16.0.147]
        ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
      register: output
    - name: Print the servers information
      ansible.builtin.debug:
        var: output.servers
