# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml
# and generated SSH key pair in location: ~/.ssh/
# In addition, this example assumes that there are already tags named "Environment" and "Department".

- name: Example
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  tasks:
    - name: Create new server | tags example
      phoenixnap.bmc.server:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
        hostnames: my-server-1
        description: My custom server 1
        location: PHX
        os: ubuntu/bionic
        type: s0.d1.medium
        configuration_type: USER_DEFINED
        tags:
          - name: Environment
            value: PROD
          - name: Department
            value: Marketing
        ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
      register: output
    - name: Print the servers information
      ansible.builtin.debug:
        var: output.servers
