# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml

- name: Example
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  tasks:
    - name: Show all servers
      phoenixnap.bmc.server_info:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
        # filter by hostname
        # hostnames: [my-server-1, my-server-2]
      register: output
    - name: Print the gathered infos
      ansible.builtin.debug:
        var: output.servers
