# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml
# Playbook can also be used for states: absent, powered-on, powered-off, rebooted

- name: Example
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  tasks:
    - name: Shutdown servers
      phoenixnap.bmc.server:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
        hostnames: [my-server-1, my-server-2]
        state: shutdown
      register: output
    - name: Print the servers information
      ansible.builtin.debug:
        var: output.servers
